In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [63]:
latlong = pd.read_csv('district wise centroids.csv')
latlong.shape

(594, 4)

In [64]:
# find is there is any null
latlong.isnull().sum()

State        0
District     0
Latitude     0
Longitude    0
dtype: int64

In [65]:
# is duplicate
latlong[latlong.duplicated()]

Empty DataFrame
Columns: [State, District, Latitude, Longitude]
Index: []

In [66]:
census = pd.read_csv('india-districts-census-2011.csv')

In [67]:
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [68]:
census.head(2)

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066

In [69]:
col =['District code','District name','Population','Male','Female','Literate','Households_with_Internet']

In [70]:
census=census[col]

In [71]:
census.rename(columns={'District name':'District'},inplace=True)

In [72]:
final_df = latlong.merge(census,on='District')

In [73]:
final_df['Sex Ratio']= (final_df['Female'] / final_df['Male'])*1000

In [74]:
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Sex Ratio
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,1001.493140
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,976.826294
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,996.964890
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1005.806152
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1002.774408
...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,5357,944.316492
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,7951,958.285781
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,12787,947.268940
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,3551,957.329879
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,2883,938.753090

In [75]:
final_df['literacy_rate'] = (final_df['Literate'] / final_df['Population'])*100

In [76]:
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Sex Ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,1001.493140,54.112283
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,976.826294,56.625244
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,996.964890,63.915599
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1005.806152,63.802642
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1002.774408,60.567804
...,...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,5357,944.316492,52.306670
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,7951,958.285781,57.093809
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,12787,947.268940,67.353414
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,3551,957.329879,55.455332
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,2883,938.753090,49.537766

In [78]:
final_df.drop(columns=['Male','Female','Literate'],inplace=True)

In [80]:
final_df.to_csv('india.csv',index=False)

In [81]:
list_of_state = list(final_df['State'].unique())

In [82]:
list_of_state.insert(0,'Overall India')

In [83]:
list_of_state

['Overall India',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [88]:
sorted(final_df.columns[5:])

['Households_with_Internet', 'Population', 'Sex Ratio', 'literacy_rate']

In [92]:
import plotly.express as px
df = px.data.carshare
fig = px.scatter_mapbox(final_df,lat='Latitude',lon='Longitude'
                          ,zoom=3,mapbox_style='carto-positron')
fig.show()

C:\Users\soura\AppData\Local\Temp\ipykernel_16224\3704454017.py:3: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/